#!/bin/bash

wallpaper=${1-.}
backend=${2-haishoku}

echo "wallpaper: $wallpaper";
echo "Backend: $backend";

# $sh userReg-flags.sh -f 'John Smith' -a 25 -u john
# echo "${foo:-"DefaultValueIfFooIsMissingOrEmpty"}"

rm -rf $HOME/.cache/swww

swww kill
swww init
swww img $wallpaper


wal -c
wal -i $wallpaper --backend ${backend:-"haishoku"}


hyprctl reload

if [[ $(pgrep -x "waybar") > 0 ]];
then
pkill -f waybar && waybar &
else
waybar &
fi


# ===================
# ====== dunst ======
# ===================

mkdir -p  "${HOME}/.config/dunst"
ln -sf    "${HOME}/.cache/wal/dunstrc"    "${HOME}/.config/dunst/dunstrc"

# Restart dunst with the new color scheme
pkill dunst
dunst &
