#!/bin/bash

default_wallpaper=`cat /home/zheng/.cache/wal/wal`
default_backend=`cat /home/zheng/.cache/wal/backend`

if [ -z "$default_backend" ]
  then
    default_backend=haishoku
fi


wallpaper=${1-$default_wallpaper}
backend=${2-$default_backend}

echo $backend > /home/zheng/.cache/wal/backend

echo "wallpaper: $wallpaper";
echo "Backend: $backend";

rm -rf $HOME/.cache/swww

swww kill
swww init
swww img $wallpaper


wal -c
wal -i $wallpaper --backend ${backend:-"haishoku"}


hyprctl reload

if [[ $(pgrep -x "waybar") > 0 ]];
then
pkill -f waybar && waybar &
else
waybar &
fi


# ===================
# ====== dunst ======
# ===================

mkdir -p  "${HOME}/.config/dunst"
ln -sf    "${HOME}/.cache/wal/dunstrc"    "${HOME}/.config/dunst/dunstrc"

# Restart dunst with the new color scheme
pkill dunst
dunst &
