############### exec-once ###############
#wallpaper
exec-once=swww init
exec-once=wal -R

#cosmetics
exec-once=waybar
#notif daemon


exec-once=dunst
#clipboard stuff
# exec-once = wl-paste --type text --watch cliphist store #Stores only text data
# exec-once = wl-paste --type image --watch cliphist store #Stores only image data

#misc
exec-once=/usr/lib/polkit-kde-authentication-agent-1
exec=once=/home/zheng/.config/hypr/xdg-portal-hyprland


################ startup apps ##################



windowrule=workspace 1 silent, kitty
windowrule=workspace 2 silent, $browser
windowrule=workspace 3 silent, discord
windowrule=workspace 4 silent, spotify

exec-once=kitty
exec-once=$browser
exec-once=discord
# exec-once=spotify

exec=~/.config/hypr/scripts/cleanup_after_start.sh
